# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/pll_main/pll_main.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_main || ORIG_REF_NAME==pll_main} -quiet] -quiet
