# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.cache/wt [current_project]
set_property parent.project_path C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/FasleJadid/Desktop/final-project/project_final/project_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/global.sv
set_property file_type "Verilog Header" [get_files C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/global.sv]
read_verilog -library xil_defaultlib -sv {
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/bhv_1w1r_sram.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/capture.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/cnn.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/draw_rectangle.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/lenet.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/lenet_roms.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/misc.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/osd.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/pll_main_clk_wiz.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/pll_main_stub.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/xilinx_1w1r_sram.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/xilinx_srams.sv
  C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/imports/source/lenet_top.sv
}
read_ip -quiet C:/Users/FasleJadid/Desktop/final-project/project_final/project_final.srcs/sources_1/ip/pll_main/pll_main.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xcku040-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
